# Generated by Django 4.2.7 on 2024-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendventures', '0002_alter_friendventure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendventure',
            name='image',
            field=models.ImageField(blank=True, default='../Friendventure_default_swdkd8', upload_to='images/'),
        ),
    ]
